jekyll.environment: production

title: Thomas Perron's Blog
google_analytics: G-XLQ43B3GT7

# Build settings
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/ths83" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/thomasperron" }
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
